[projet]
nom = "nol-i18n"
version = "0.2.0"
entree = "src/lib.nol"
auteur = "daliranas <bastien@languedoc.ovh>"
licence = "MIT"
description = "Traductions et pluriels CLDR (zero/one/two/few/many/other) + formatage de nombres par locale, en pur Nolc."

[dependances]
